version: '3.9'

services:
  book-store:
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: npm start
    depends_on:
      - views-counter

  views-counter:
    image: fanich37/views-counter
    volumes:
      - './storage:/var/www/view-counter/storage'
    ports:
      - '3002:8080'
